# Generated by Django 6.0.5 on 2026-06-13 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_savedflashcard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('mascot_name', models.CharField(blank=True, default='Foxy', max_length=40)),
                ('mascot_species', models.CharField(blank=True, default='fox', max_length=20)),
                ('grade_level', models.IntegerField(default=4)),
                ('xp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_mission_date', models.DateField(blank=True, null=True)),
                ('total_missions', models.IntegerField(default=0)),
                ('total_correct', models.IntegerField(default=0)),
                ('total_items', models.IntegerField(default=0)),
                ('subject_stats', models.JSONField(blank=True, default=dict)),
                ('seen_items', models.JSONField(blank=True, default=dict)),
                ('badges', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_date', models.DateField()),
                ('items_json', models.JSONField(blank=True, default=list)),
                ('is_recovery', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('xp_earned', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='trainer.playerprofile')),
            ],
            options={
                'ordering': ['-mission_date', '-created_at'],
            },
        ),
    ]
