# Generated by Django 6.0.5 on 2026-06-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_playerprofile_missionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='dyslexia_font',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='high_contrast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='large_text',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='reduce_motion',
            field=models.BooleanField(default=False),
        ),
    ]
