"""
Math Challenge content.
Loads questions from cached JSON (OCR'd PDFs) + 35 hand-crafted Kimi problems with
full hints, step-by-step explanations, and key concepts.
"""
import random
from datetime import date
from .pdf_extractor import load_cached_only

# ── 35 hand-crafted Kimi problems ────────────────────────────────────────────
KIMI_QUESTIONS = [
    {
        'id': 'ki_001', 'grade': 4, 'age_min': 8, 'age_max': 12,
        'question': 'Look at this addition problem:\n\n  3 A 5 4\n  2 6 2 B\n+ C 7 9 3\n───────\n  7 7 7 4\n\nEach letter (A, B, C) stands for a digit. What is A + B + C?',
        'type': 'mcq',
        'options': {'A': '7', 'B': '9', 'C': '10', 'D': '11'},
        'answer': 'D',
        'topic': 'Number Puzzles', 'difficulty': 'olympiad', 'source': 'Math Quest',
        'points': 1,
        'hint': 'Start from the ones place (rightmost column). What number plus 4 plus 3 gives you 4 or 14?',
        'steps': [
            'Start from the ones place: 4 + B + 3 = 14 (with carry), so B = 7.',
            'Tens place with carry 1: 5 + 2 + 9 + 1 = 17. Write 7, carry 1.',
            'Hundreds place with carry 1: A + 6 + 7 + 1 = 17, so A = 3.',
            'Thousands place with carry 1: 3 + 2 + C + 1 = 7, so C = 1.',
            'A + B + C = 3 + 7 + 1 = 11 ✓',
        ],
        'key_concept': 'When solving digit puzzles, always start from the ones place (right side) and work left. Track carry-overs carefully!',
        'image': None,
    },
    {
        'id': 'ki_002', 'grade': 4, 'age_min': 8, 'age_max': 12,
        'question': '1899 + MNP = 1217 + 1666\n\nIf MNP is a three-digit number, find MNP.',
        'type': 'mcq',
        'options': {'A': '943', 'B': '498', 'C': '894', 'D': '984'},
        'answer': 'D',
        'topic': 'Algebra', 'difficulty': 'olympiad', 'source': 'Math Quest',
        'points': 2,
        'hint': 'First figure out what 1217 + 1666 equals. Then use that to find MNP!',
        'steps': [
            'Calculate the right side: 1217 + 1666 = 2883.',
            'Now: 1899 + MNP = 2883.',
            'MNP = 2883 − 1899 = 984.',
            'Check: 1899 + 984 = 2883 ✓',
        ],
        'key_concept': 'When a letter stands for a number, simplify what you can first, then use the opposite operation (subtraction) to find the unknown!',
        'image': None,
    },
    {
        'id': 'ki_003', 'grade': 4, 'age_min': 8, 'age_max': 12,
        'question': 'Look at this number pattern:\n\n6, ★, 20, ●, 34, 41, ...\n\nHow much more is ● than ★?',
        'type': 'mcq',
        'options': {'A': '14', 'B': '15', 'C': '16', 'D': '17'},
        'answer': 'A',
        'topic': 'Number Patterns', 'difficulty': 'olympiad', 'source': 'Math Quest',
        'points': 3,
        'hint': 'Look at the known numbers: 34 and 41. What is the difference? That is probably the pattern rule!',
        'steps': [
            '41 − 34 = 7. The rule is: add 7 each time.',
            '★ = 6 + 7 = 13. Check: 13 + 7 = 20 ✓',
            '● = 20 + 7 = 27. Check: 27 + 7 = 34 ✓',
            '● − ★ = 27 − 13 = 14.',
        ],
        'key_concept': 'To find a pattern rule, look at consecutive known values and find the difference between them!',
        'image': None,
    },
    {
        'id': 'ki_004', 'grade': 4, 'age_min': 8, 'age_max': 12,
        'question': 'A greengrocer bought 148 crates of tomatoes. Each crate contained 19 kg. He wants to sell in 4 kg packages. How many packages does he need?',
        'type': 'mcq',
        'options': {'A': '703', 'B': '73', 'C': '42', 'D': '402'},
        'answer': 'A',
        'topic': 'Word Problems', 'difficulty': 'olympiad', 'source': 'Math Quest',
        'points': 4,
        'hint': 'First find the total weight of all tomatoes. Then figure out how many 4 kg packages you can make.',
        'steps': [
            'Total weight = 148 crates × 19 kg = 2812 kg.',
            'Number of packages = 2812 ÷ 4 = 703.',
        ],
        'key_concept': 'In multi-step word problems, find the total first, then divide into groups!',
        'image': None,
    },
    {
        'id': 'ki_005', 'grade': 4, 'age_min': 8, 'age_max': 12,
        'question': 'Clues about four children:\n• Jack is older than Lily.\n• Lily is younger than Alex but older than Melissa.\n• Alex is older than Jack.\n\nRanked oldest to youngest — who is 2nd?',
        'type': 'mcq',
        'options': {'A': 'Jack', 'B': 'Lily', 'C': 'Alex', 'D': 'Melissa'},
        'answer': 'A',
        'topic': 'Logic', 'difficulty': 'olympiad', 'source': 'Math Quest',
        'points': 5,
        'hint': 'Write each clue with > symbols (older than). Then chain them together.',
        'steps': [
            'Jack > Lily (clue 1).',
            'Alex > Lily > Melissa (clue 2).',
            'Alex > Jack (clue 3).',
            'Combined: Alex > Jack > Lily > Melissa.',
            '2nd place = Jack.',
        ],
        'key_concept': 'Use > and < to write "older than" clues, then chain them into one ordering!',
        'image': None,
    },
    {
        'id': 'ki_006', 'grade': 4, 'age_min': 8, 'age_max': 12,
        'question': 'The figure is made of square pieces. What is the minimum number of extra squares needed to complete it into the smallest possible rectangle?',
        'type': 'mcq',
        'options': {'A': '24', 'B': '28', 'C': '30', 'D': '32'},
        'answer': 'B',
        'topic': 'Geometry', 'difficulty': 'olympiad', 'source': 'Math Quest',
        'points': 6,
        'hint': 'Count how many squares the final rectangle should have. Subtract what you already have.',
        'steps': [
            'The smallest enclosing rectangle is 8 × 7 = 56 squares.',
            'Squares already in the figure = 28.',
            'Extra squares needed = 56 − 28 = 28.',
        ],
        'key_concept': 'Find the total size of the complete shape, then subtract what you already have!',
        'image': 'math_problems/page_2.png',
    },
    {
        'id': 'ki_007', 'grade': 4, 'age_min': 8, 'age_max': 12,
        'question': 'On a farm, chickens = 5 × roosters, and total birds = 366. How many chickens?',
        'type': 'mcq',
        'options': {'A': '61', 'B': '305', 'C': '73', 'D': '102'},
        'answer': 'B',
        'topic': 'Word Problems', 'difficulty': 'olympiad', 'source': 'Math Quest',
        'points': 1,
        'hint': '1 rooster + 5 chickens = 6 birds. How many groups of 6 fit in 366?',
        'steps': [
            'Let R = roosters. Chickens = 5R.',
            'R + 5R = 6R = 366, so R = 61.',
            'Chickens = 5 × 61 = 305.',
        ],
        'key_concept': 'When one quantity is a multiple of another, write an equation and solve!',
        'image': None,
    },
    {
        'id': 'ki_008', 'grade': 4, 'age_min': 8, 'age_max': 12,
        'question': 'The triple of 106 is added to the quintuple of 95. What is the result?',
        'type': 'mcq',
        'options': {'A': '318', 'B': '475', 'C': '1608', 'D': '793'},
        'answer': 'D',
        'topic': 'Multiplication', 'difficulty': 'olympiad', 'source': 'Math Quest',
        'points': 1,
        'hint': '"Triple" = ×3. "Quintuple" = ×5. Multiply each, then add.',
        'steps': [
            'Triple of 106 = 3 × 106 = 318.',
            'Quintuple of 95 = 5 × 95 = 475.',
            '318 + 475 = 793.',
        ],
        'key_concept': 'Triple = ×3, quadruple = ×4, quintuple = ×5. Learn these vocabulary words!',
        'image': None,
    },
    {
        'id': 'ki_009', 'grade': 4, 'age_min': 8, 'age_max': 12,
        'question': '(3059 × 4) − 879 < ⬜\n\nWhat is the smallest possible whole-number value of ⬜?',
        'type': 'mcq',
        'options': {'A': '11357', 'B': '11457', 'C': '11356', 'D': '11358'},
        'answer': 'D',
        'topic': 'Inequalities', 'difficulty': 'olympiad', 'source': 'Math Quest',
        'points': 1,
        'hint': 'Calculate the left side first. The box must be BIGGER than that result — so what is the very next whole number?',
        'steps': [
            '3059 × 4 = 12236.',
            '12236 − 879 = 11357.',
            'We need ⬜ > 11357. Smallest whole number = 11358.',
        ],
        'key_concept': 'If X < ⬜, the smallest integer value of ⬜ is X + 1!',
        'image': None,
    },
    {
        'id': 'ki_010', 'grade': 4, 'age_min': 8, 'age_max': 12,
        'question': 'An athlete needs to run 8746 m total over 3 days. Day 1: 2104 m, Day 2: 3099 m. How far on Day 3?',
        'type': 'mcq',
        'options': {'A': '5203', 'B': '5647', 'C': '3543', 'D': '3647'},
        'answer': 'C',
        'topic': 'Subtraction', 'difficulty': 'olympiad', 'source': 'Math Quest',
        'points': 1,
        'hint': 'Add Days 1 and 2, then subtract from the total.',
        'steps': [
            'Days 1 + 2 = 2104 + 3099 = 5203 m.',
            'Day 3 = 8746 − 5203 = 3543 m.',
        ],
        'key_concept': 'To find the remaining amount, subtract what is already used from the total!',
        'image': None,
    },
    {
        'id': 'ki_011', 'grade': 4, 'age_min': 8, 'age_max': 12,
        'question': 'The product of two numbers is 392. One factor is 8. What is the other factor?',
        'type': 'mcq',
        'options': {'A': '49', 'B': '48', 'C': '39', 'D': '36'},
        'answer': 'A',
        'topic': 'Division', 'difficulty': 'olympiad', 'source': 'Math Quest',
        'points': 2,
        'hint': '"Product" means multiplication. Use division to find the missing factor.',
        'steps': [
            '8 × ? = 392.',
            '? = 392 ÷ 8 = 49.',
            'Check: 8 × 49 = 392 ✓',
        ],
        'key_concept': 'Product = multiplication result. To find a missing factor, divide the product by the known factor!',
        'image': None,
    },
    {
        'id': 'ki_012', 'grade': 4, 'age_min': 8, 'age_max': 12,
        'question': '18018 ÷ 18 — which statement is correct?',
        'type': 'mcq',
        'options': {'A': 'The quotient has three digits.', 'B': 'The quotient has two zeros.', 'C': 'The quotient has one zero.', 'D': 'The quotient is the greatest three-digit number.'},
        'answer': 'B',
        'topic': 'Division', 'difficulty': 'olympiad', 'source': 'Math Quest',
        'points': 2,
        'hint': 'Do the division first. What is 18018 ÷ 18?',
        'steps': [
            '18018 ÷ 18 = 1001.',
            '1001 has four digits (not three), so A and D are wrong.',
            '1001 has TWO zeros — so B is correct!',
        ],
        'key_concept': 'Always calculate first, then check each statement against your result.',
        'image': None,
    },
    {
        'id': 'ki_013', 'grade': 4, 'age_min': 8, 'age_max': 12,
        'question': '3 kg + 2000 mg + 45 g = ? g',
        'type': 'mcq',
        'options': {'A': '2048', 'B': '347', 'C': '3047', 'D': '5045'},
        'answer': 'C',
        'topic': 'Measurement (Mass)', 'difficulty': 'olympiad', 'source': 'Math Quest',
        'points': 2,
        'hint': 'Convert everything to grams. 1 kg = 1000 g, 1 g = 1000 mg.',
        'steps': [
            '3 kg = 3000 g.',
            '2000 mg = 2 g.',
            '45 g = 45 g.',
            '3000 + 2 + 45 = 3047 g.',
        ],
        'key_concept': 'When adding measurements, convert to the SAME unit first!',
        'image': None,
    },
    {
        'id': 'ki_014', 'grade': 4, 'age_min': 8, 'age_max': 12,
        'question': "Oliver's step is 65 cm. He takes 140 steps to walk to school. What is the distance in meters?",
        'type': 'mcq',
        'options': {'A': '9100', 'B': '910', 'C': '91', 'D': '90'},
        'answer': 'C',
        'topic': 'Measurement (Length)', 'difficulty': 'olympiad', 'source': 'Math Quest',
        'points': 2,
        'hint': 'Distance in cm = step × steps. Then convert cm to m by dividing by 100.',
        'steps': [
            '65 cm × 140 = 9100 cm.',
            '9100 ÷ 100 = 91 meters.',
        ],
        'key_concept': '1 meter = 100 centimeters. Divide centimeters by 100 to get meters!',
        'image': None,
    },
    {
        'id': 'ki_015', 'grade': 4, 'age_min': 8, 'age_max': 12,
        'question': 'Emma bought: ¼ kg onions, 1 kg 250 g tomatoes, 4.5 kg potatoes, 3.5 kg oranges, ½ kg bananas. Total weight in kg?',
        'type': 'mcq',
        'options': {'A': '8', 'B': '9', 'C': '10', 'D': '11'},
        'answer': 'C',
        'topic': 'Measurement (Mass)', 'difficulty': 'olympiad', 'source': 'Math Quest',
        'points': 3,
        'hint': 'Convert all to kg first. Quarter = 0.25, half = 0.5, 250 g = 0.25 kg.',
        'steps': [
            'Onions: 0.25 kg.',
            'Tomatoes: 1.25 kg.',
            'Potatoes: 4.5 kg.',
            'Oranges: 3.5 kg.',
            'Bananas: 0.5 kg.',
            'Total = 0.25 + 1.25 + 4.5 + 3.5 + 0.5 = 10 kg.',
        ],
        'key_concept': 'Quarter (¼) = 0.25, half (½) = 0.5. Convert fractions to decimals before adding!',
        'image': None,
    },
    {
        'id': 'ki_016', 'grade': 4, 'age_min': 8, 'age_max': 12,
        'question': 'How much is 10 quarter-liters less than 5 liters?',
        'type': 'mcq',
        'options': {'A': '2 liters', 'B': '2 and a half liters', 'C': '2 liters and 250 mL', 'D': '3 liters'},
        'answer': 'B',
        'topic': 'Measurement (Volume)', 'difficulty': 'olympiad', 'source': 'Math Quest',
        'points': 3,
        'hint': 'A quarter-liter = 0.25 L. How much are 10 quarter-liters? Then subtract from 5.',
        'steps': [
            '10 × ¼ L = 2.5 L.',
            '5 − 2.5 = 2.5 liters = 2 and a half liters.',
        ],
        'key_concept': 'Quarter-liter = 0.25 L. Ten quarters equal 2.5, just like ten 25-cent coins equal $2.50!',
        'image': None,
    },
    {
        'id': 'ki_017', 'grade': 4, 'age_min': 8, 'age_max': 12,
        'question': 'A square field has side 20 m. It will be surrounded by 4 rows of wire. How many meters of wire?',
        'type': 'mcq',
        'options': {'A': '200', 'B': '240', 'C': '320', 'D': '400'},
        'answer': 'C',
        'topic': 'Area & Perimeter', 'difficulty': 'olympiad', 'source': 'Math Quest',
        'points': 3,
        'hint': 'Find the perimeter (one row). Then multiply by 4.',
        'steps': [
            'Perimeter = 4 × 20 = 80 m.',
            '4 rows × 80 m = 320 m of wire.',
        ],
        'key_concept': 'Perimeter of square = 4 × side. Multiple rows = perimeter × number of rows!',
        'image': None,
    },
    {
        'id': 'ki_018', 'grade': 4, 'age_min': 8, 'age_max': 12,
        'question': 'The perimeter of a square is 36 cm. What is its area?',
        'type': 'mcq',
        'options': {'A': '9', 'B': '49', 'C': '64', 'D': '81'},
        'answer': 'D',
        'topic': 'Area & Perimeter', 'difficulty': 'olympiad', 'source': 'Math Quest',
        'points': 3,
        'hint': 'Find the side first: Perimeter = 4 × side. Then area = side × side.',
        'steps': [
            'Side = 36 ÷ 4 = 9 cm.',
            'Area = 9 × 9 = 81 cm².',
        ],
        'key_concept': 'Find the side from the perimeter first, then calculate area = side²!',
        'image': None,
    },
    {
        'id': 'ki_019', 'grade': 4, 'age_min': 8, 'age_max': 12,
        'question': 'A shape has perimeter 68 cm. Known sides: 15, 10, 9, 2, 2, 3, 20 cm. What is the missing side?',
        'type': 'mcq',
        'options': {'A': '4', 'B': '6', 'C': '7', 'D': '9'},
        'answer': 'C',
        'topic': 'Area & Perimeter', 'difficulty': 'olympiad', 'source': 'Math Quest',
        'points': 4,
        'hint': 'Add all known sides, then subtract from the total perimeter.',
        'steps': [
            'Known sides total: 15+10+9+2+2+3+20 = 61.',
            'Missing side = 68 − 61 = 7 cm.',
        ],
        'key_concept': 'Perimeter = sum of ALL sides. Missing side = total perimeter − sum of known sides!',
        'image': None,
    },
    {
        'id': 'ki_020', 'grade': 4, 'age_min': 8, 'age_max': 12,
        'question': 'A grasshopper jumps: 1st jump = 120 cm. Each jump is 40 cm more than the last. Total distance after 5 jumps?',
        'type': 'mcq',
        'options': {'A': '1 km', 'B': '600 cm', 'C': '10 m', 'D': '760 cm'},
        'answer': 'C',
        'topic': 'Number Patterns', 'difficulty': 'olympiad', 'source': 'Math Quest',
        'points': 4,
        'hint': 'List all 5 jumps: 120, 160, 200, 240, 280. Add them up.',
        'steps': [
            'Jump 1: 120 cm, Jump 2: 160 cm, Jump 3: 200 cm, Jump 4: 240 cm, Jump 5: 280 cm.',
            'Total = 120+160+200+240+280 = 1000 cm.',
            '1000 cm = 10 m.',
        ],
        'key_concept': 'In a sequence adding the same amount each time, list each term and add them all!',
        'image': None,
    },
    {
        'id': 'ki_021', 'grade': 4, 'age_min': 8, 'age_max': 12,
        'question': '⅙ hour + 2220 seconds − 12 minutes = ? minutes',
        'type': 'mcq',
        'options': {'A': '35', 'B': '59', 'C': '183', 'D': '192'},
        'answer': 'A',
        'topic': 'Measurement (Time)', 'difficulty': 'olympiad', 'source': 'Math Quest',
        'points': 4,
        'hint': 'Convert everything to minutes. ⅙ hour = 10 min. 2220 s ÷ 60 = 37 min.',
        'steps': [
            '⅙ hour = 60 ÷ 6 = 10 minutes.',
            '2220 seconds ÷ 60 = 37 minutes.',
            '10 + 37 − 12 = 35 minutes.',
        ],
        'key_concept': '1 hour = 60 minutes, 1 minute = 60 seconds. Always convert to the same unit first!',
        'image': None,
    },
    {
        'id': 'ki_022', 'grade': 4, 'age_min': 8, 'age_max': 12,
        'question': 'A 3D shape has layers: Bottom = 5 cubes, Middle = 2 cubes, Top = 1 cube. How many cubes total?',
        'type': 'mcq',
        'options': {'A': '5', 'B': '6', 'C': '8', 'D': '9'},
        'answer': 'C',
        'topic': 'Geometry', 'difficulty': 'olympiad', 'source': 'Math Quest',
        'points': 4,
        'hint': 'Count cubes layer by layer and add.',
        'steps': [
            'Bottom: 5 cubes.',
            'Middle: 2 cubes.',
            'Top: 1 cube.',
            'Total = 5 + 2 + 1 = 8 cubes.',
        ],
        'key_concept': 'Count cubes layer by layer. Include hidden supporting cubes!',
        'image': None,
    },
    {
        'id': 'ki_023', 'grade': 4, 'age_min': 8, 'age_max': 12,
        'question': 'A cube net has faces: 4 (top row), 2-5-6-1 (middle row), 3 (bottom row). When folded, which arrangement is IMPOSSIBLE?',
        'type': 'mcq',
        'options': {'A': '4 on top, 2 and 6 on sides', 'B': '5 on top, 2 and 6 on sides', 'C': '2 and 6 next to each other as sides', 'D': '4 on top, 5 and 3 on sides'},
        'answer': 'C',
        'topic': 'Geometry', 'difficulty': 'olympiad', 'source': 'Math Quest',
        'points': 5,
        'hint': 'In the net, 2 and 6 are opposite faces. Opposite faces can NEVER be adjacent on a real cube!',
        'steps': [
            'Opposite faces in this net: 4↔3, 2↔6, 5↔1.',
            'Option C says 2 and 6 are adjacent — but they are opposite!',
            'Opposite faces can never touch → Option C is impossible.',
        ],
        'key_concept': 'Opposite faces on a cube can never be next to each other. Identify opposite pairs from the net first!',
        'image': None,
    },
    {
        'id': 'ki_024', 'grade': 4, 'age_min': 8, 'age_max': 12,
        'question': 'How much should be added to the largest 5-digit number to get the smallest 6-digit odd number?',
        'type': 'mcq',
        'options': {'A': '2', 'B': '11112', 'C': '11111', 'D': '1000'},
        'answer': 'A',
        'topic': 'Number Sense', 'difficulty': 'olympiad', 'source': 'Math Quest',
        'points': 5,
        'hint': 'Largest 5-digit = 99999. Smallest 6-digit odd = 100001 (since 100000 is even).',
        'steps': [
            'Largest 5-digit number = 99999.',
            'Smallest 6-digit number = 100000 (even).',
            'Smallest 6-digit odd number = 100001.',
            '100001 − 99999 = 2.',
        ],
        'key_concept': 'Odd numbers end in 1, 3, 5, 7, or 9. The smallest 6-digit odd number is 100001!',
        'image': None,
    },
    {
        'id': 'ki_025', 'grade': 4, 'age_min': 8, 'age_max': 12,
        'question': 'A shop has 5108 green notebooks and 6864 lined notebooks. 3004 are purple lined. How many green checkered notebooks?',
        'type': 'mcq',
        'options': {'A': '1248', 'B': '1756', 'C': '2104', 'D': '3860'},
        'answer': 'A',
        'topic': 'Word Problems', 'difficulty': 'olympiad', 'source': 'Math Quest',
        'points': 5,
        'hint': 'Find green lined notebooks first. Then subtract from total green to get green checkered.',
        'steps': [
            'Green lined = 6864 − 3004 = 3860.',
            'Green checkered = 5108 − 3860 = 1248.',
        ],
        'key_concept': 'Organise overlapping categories with Total = Part A + Part B. Subtract to find unknowns!',
        'image': None,
    },
    {
        'id': 'ki_026', 'grade': 4, 'age_min': 8, 'age_max': 12,
        'question': '128 passengers on a bus.\nStop 1: 24 board, 19 alight.\nStop 2: 32 board, 13 alight.\nStop 3: 18 board, 23 alight.\nHow many at the end?',
        'type': 'mcq',
        'options': {'A': '53', 'B': '120', 'C': '144', 'D': '147'},
        'answer': 'D',
        'topic': 'Word Problems', 'difficulty': 'olympiad', 'source': 'Math Quest',
        'points': 5,
        'hint': 'Track the running total at each stop. Boarded = add, Alighted = subtract.',
        'steps': [
            'Start: 128.',
            'Stop 1: 128 + 24 − 19 = 133.',
            'Stop 2: 133 + 32 − 13 = 152.',
            'Stop 3: 152 + 18 − 23 = 147.',
        ],
        'key_concept': '"Boarded" = add, "alighted/got off" = subtract. Track the running total!',
        'image': None,
    },
    {
        'id': 'ki_027', 'grade': 4, 'age_min': 8, 'age_max': 12,
        'question': 'Ducks = 4 × rabbits. Total legs = 1404. (Ducks: 2 legs, Rabbits: 4 legs.) How many rabbits?',
        'type': 'mcq',
        'options': {'A': '107', 'B': '117', 'C': '123', 'D': '132'},
        'answer': 'B',
        'topic': 'Algebra', 'difficulty': 'olympiad', 'source': 'Math Quest',
        'points': 6,
        'hint': 'If R = rabbits, ducks = 4R. Rabbit legs = 4R, duck legs = 8R. Total = 12R = 1404.',
        'steps': [
            'Let R = rabbits. Ducks = 4R.',
            'Rabbit legs = 4R. Duck legs = 2 × 4R = 8R.',
            'Total legs: 4R + 8R = 12R = 1404.',
            'R = 1404 ÷ 12 = 117.',
        ],
        'key_concept': 'Use algebra: one letter for the unknown, then write a legs equation and solve!',
        'image': None,
    },
    {
        'id': 'ki_028', 'grade': 4, 'age_min': 8, 'age_max': 12,
        'question': "My mother's age = 4 × my age. Grandfather's age = 3 × mother's age. Sum = 136. How old is grandfather?",
        'type': 'mcq',
        'options': {'A': '72', 'B': '84', 'C': '96', 'D': '98'},
        'answer': 'C',
        'topic': 'Algebra', 'difficulty': 'olympiad', 'source': 'Math Quest',
        'points': 6,
        'hint': 'If my age = x, mother = 4x, grandfather = 12x. x + 4x + 12x = 136.',
        'steps': [
            'My age = x, Mother = 4x, Grandfather = 12x.',
            'x + 4x + 12x = 17x = 136.',
            'x = 8.',
            'Grandfather = 12 × 8 = 96.',
        ],
        'key_concept': 'Use one letter for the smallest value, express everything else as multiples, then solve!',
        'image': None,
    },
    {
        'id': 'ki_029', 'grade': 4, 'age_min': 8, 'age_max': 12,
        'question': 'If ⁶⁄₁₄ of a number is 102, what is ¹⁄₁₇ of that number?',
        'type': 'mcq',
        'options': {'A': '8', 'B': '10', 'C': '14', 'D': '17'},
        'answer': 'C',
        'topic': 'Fractions', 'difficulty': 'olympiad', 'source': 'Math Quest',
        'points': 6,
        'hint': 'Simplify ⁶⁄₁₄ = ³⁄₇. If ³⁄₇ of number = 102, find the whole number, then find ¹⁄₁₇.',
        'steps': [
            '⁶⁄₁₄ = ³⁄₇.',
            '³⁄₇ × N = 102, so ¹⁄₇ × N = 34, so N = 238.',
            '¹⁄₁₇ × 238 = 14.',
        ],
        'key_concept': '"Of" means multiply. Find 1 part by dividing, then scale up or down!',
        'image': None,
    },
    {
        'id': 'ki_030', 'grade': 4, 'age_min': 8, 'age_max': 12,
        'question': 'Each number divided by 14. Which gives a result that is NOT two digits: 126, 504, 378, or 1022?',
        'type': 'mcq',
        'options': {'A': '126', 'B': '504', 'C': '378', 'D': '1022'},
        'answer': 'A',
        'topic': 'Division', 'difficulty': 'olympiad', 'source': 'Math Quest',
        'points': 6,
        'hint': 'A two-digit result is 10–99. Which division gives a 1-digit answer?',
        'steps': [
            '126 ÷ 14 = 9 (one digit!)',
            '504 ÷ 14 = 36, 378 ÷ 14 = 27, 1022 ÷ 14 = 73 (all two digits).',
            'Only 126 gives a single-digit result → leaf 126 is torn off.',
        ],
        'key_concept': 'Two-digit numbers are 10 to 99. Calculate each and check the digit count!',
        'image': None,
    },
    {
        'id': 'ki_031', 'grade': 4, 'age_min': 8, 'age_max': 12,
        'question': 'A cube has faces: Smiley, Star, Flower, Teacup, Ladybug, Crayon. Which opposite pairs are correct?',
        'type': 'mcq',
        'options': {'A': 'Smiley-Star, Flower-Teacup, Ladybug-Crayon', 'B': 'Smiley-Crayon, Star-Teacup, Flower-Ladybug', 'C': 'Smiley-Flower, Star-Ladybug, Teacup-Crayon', 'D': 'Smiley-Teacup, Star-Crayon, Flower-Ladybug'},
        'answer': 'B',
        'topic': 'Geometry', 'difficulty': 'olympiad', 'source': 'Math Quest',
        'points': 7,
        'hint': 'In the cube net, the top and bottom faces are opposite. Middle row: 1st and 3rd in a row of 4 wrap to be opposite.',
        'steps': [
            'Top row (Smiley) folds down → opposite to bottom row (Crayon).',
            'Middle row wraps around: Star ↔ Teacup.',
            'Flower ↔ Ladybug.',
            'Answer: Smiley-Crayon, Star-Teacup, Flower-Ladybug.',
        ],
        'key_concept': 'In a cube net, adjacent faces in a straight line of 4 wrap to be opposite!',
        'image': None,
    },
    {
        'id': 'ki_032', 'grade': 4, 'age_min': 8, 'age_max': 12,
        'question': 'Triangle pattern: Step 1 = 7, Step 2 = 10, Step 3 = 13, +3 each step. In which step are there 31 triangles?',
        'type': 'mcq',
        'options': {'A': 'Step 8', 'B': 'Step 9', 'C': 'Step 10', 'D': 'Step 11'},
        'answer': 'B',
        'topic': 'Number Patterns', 'difficulty': 'olympiad', 'source': 'Math Quest',
        'points': 7,
        'hint': 'Formula: triangles = 7 + 3 × (step − 1). Set = 31 and solve for step.',
        'steps': [
            'Formula: 7 + 3(step − 1) = 31.',
            '3(step − 1) = 24.',
            'step − 1 = 8, so step = 9.',
        ],
        'key_concept': 'Pattern formula: start + difference × (step − 1). Set it equal to the target and solve!',
        'image': None,
    },
    {
        'id': 'ki_033', 'grade': 4, 'age_min': 8, 'age_max': 12,
        'question': 'Three circles each sum to 60.\nCircle 1: 15, 8, 9, 🌳, 🌸\nCircle 2: 🌳, 🌸, 7, 15, ☀️\nCircle 3: 15, 12, 6, ⭐, ☀️\nWhat is ⭐?',
        'type': 'mcq',
        'options': {'A': '17', 'B': '19', 'C': '27', 'D': '29'},
        'answer': 'A',
        'topic': 'Logic', 'difficulty': 'olympiad', 'source': 'Math Quest',
        'points': 7,
        'hint': 'From Circle 1 find 🌳 + 🌸. Use that in Circle 2 to find ☀️. Then use ☀️ in Circle 3 for ⭐.',
        'steps': [
            'Circle 1: 15+8+9+🌳+🌸 = 60 → 🌳+🌸 = 28.',
            'Circle 2: 28+7+15+☀️ = 60 → ☀️ = 10.',
            'Circle 3: 15+12+6+⭐+10 = 60 → ⭐ = 17.',
        ],
        'key_concept': 'In overlapping circle puzzles, find shared values first, then substitute step by step!',
        'image': None,
    },
    {
        'id': 'ki_034', 'grade': 4, 'age_min': 8, 'age_max': 12,
        'question': 'Scale I: 1 cuboid + 1 cylinder + 2 pyramids = 3 cylinders\nScale II: 1 cylinder = 3 pyramids\n\nScale III: 1 cuboid + 1 cylinder = ? pyramids',
        'type': 'mcq',
        'options': {'A': '5', 'B': '6', 'C': '7', 'D': '11'},
        'answer': 'C',
        'topic': 'Algebra', 'difficulty': 'olympiad', 'source': 'Math Quest',
        'points': 7,
        'hint': 'From Scale II: cylinder = 3 pyramids. Substitute into Scale I to find cuboid in pyramids.',
        'steps': [
            'Scale II: cylinder = 3 pyramids.',
            'Scale I: cuboid + 3 + 2 = 9 pyramids → cuboid = 4 pyramids.',
            'Scale III: cuboid + cylinder = 4 + 3 = 7 pyramids.',
        ],
        'key_concept': 'In balance puzzles, substitute known values step by step to find unknowns!',
        'image': None,
    },
    {
        'id': 'ki_035', 'grade': 4, 'age_min': 8, 'age_max': 12,
        'question': 'Find the puzzle piece that fits the L-shaped empty space — it must match both the shape AND the orientation.',
        'type': 'mcq',
        'options': {'A': 'Piece A (correct L-shape and orientation)', 'B': 'Piece B (wrong proportions)', 'C': 'Piece C (wrong orientation)', 'D': 'Piece D (wrong orientation)'},
        'answer': 'A',
        'topic': 'Geometry', 'difficulty': 'olympiad', 'source': 'Math Quest',
        'points': 7,
        'hint': 'Check BOTH the shape and which direction the L points.',
        'steps': [
            'The space is L-shaped with a specific orientation.',
            'Option A matches both shape and orientation perfectly.',
            'Options B, C, D have wrong proportions or orientation.',
        ],
        'key_concept': 'When matching puzzle pieces, always check both the shape AND its orientation (rotation)!',
        'image': None,
    },
]


def get_all_questions() -> list[dict]:
    """All questions: cached PDF extractions + Kimi hand-crafted."""
    cached = load_cached_only()
    cached_ids = {q['id'] for q in cached}
    extra = [q for q in KIMI_QUESTIONS if q['id'] not in cached_ids]
    return cached + extra


def filter_questions(questions: list[dict], grade: int | None = None,
                     topic: str | None = None, difficulty: str | None = None,
                     qtype: str | None = None) -> list[dict]:
    result = questions
    if grade:
        result = [q for q in result if q.get('grade') == grade]
    if topic:
        result = [q for q in result if topic.lower() in q.get('topic', '').lower()]
    if difficulty:
        result = [q for q in result if q.get('difficulty') == difficulty]
    if qtype:
        result = [q for q in result if q.get('type') == qtype]
    return result


def get_topics(questions: list[dict]) -> list[str]:
    return sorted(set(q.get('topic', 'General') for q in questions))


def get_quiz_session(questions: list[dict], count=10, seed: int | None = None) -> list[dict]:
    """Return a shuffled subset for a quiz session, Kimi questions first."""
    if seed is None:
        seed = date.today().toordinal()
    kimi = [q for q in questions if q.get('source') == 'Math Quest']
    rest = [q for q in questions if q.get('source') != 'Math Quest']
    rng = random.Random(seed)
    rng.shuffle(kimi)
    rng.shuffle(rest)
    pool = kimi + rest
    return pool[:count]
